### ISSUE TITLE
Create a ROS message to send to the point cloud for processing

### ISSUE THREAD

**Issue by TatianaResend** [andrefdre/Dora_the_mug_finder_SAVI#39]
Implement ROS messages to send the kinect point cloud (in .ply format) to retrieve objects.

**Comment by fabio-rcs** [comment]
With this [comit](https://github.com/andrefdre/Dora_the_mug_finder_SAVI/commit/65f2cfe13d77eb8d9542e6ca959b34dcdc11b509) the message containing the point cloud coming from the Kinect camera and converted into the Open3d format, is being sent under the topic **/open3d_cloud**. 
Now, it's only missing the implementation on the processing code so that we can process live information.

**Comment by fabio-rcs** [comment]
As of #44  is finished, that means this issue can also be closed.
